### PR TITLE
Curl code fix

### PR DESCRIPTION
**Pull request by s-chizhik**

### CODE REVIEW

**Comment by s-chizhik** [comment]
@mtdowling, ping

**Comment by mtdowling** [comment]
The unit tests passed before this change, so can you provide more details on why this is needed?

**Comment by s-chizhik** [comment]
Sure. A year ago I noticed, that curl filter doesn't work at all. Mistake was in two packages: `guzzle/RingPHP`, and `guzzle/retry-subscriber`. Problem was, that RingPHP doesn't pass `curl_result` to `transferInfo`, so `guzzle/retry-subscriber` can't get it :) I've created MR's to fix both packages. You've merged just [one](https://github.com/guzzle/RingPHP/pull/21) out of two. Issue was described [here](https://github.com/guzzle/retry-subscriber/issues/23).

**Comment by s-chizhik** [comment]
@mtdowling, ping

**Pull request merged**
